<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Ressources\Applicaton.ico</ApplicationIcon>
		<PackageIcon>Application.png</PackageIcon>
		<Product>Deploy Configurator WPF</Product>
		<Company>PB BZH Concept</Company>
		<Copyright>Copyright © 2026 PB BZH Concept</Copyright>
		<Version>1.0.0</Version>
		<Description>Framework de configuration de déploiement Windows automatisé</Description>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
		<ApplicationManifest>app.manifest</ApplicationManifest>

	</PropertyGroup>
	<ItemGroup>
		<Content Include="Templates\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="MainWindow.xaml.cs.old.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Ressources\alarme.png" />
	  <None Remove="Ressources\archive.png" />
	  <None Remove="Ressources\build.png" />
	  <None Remove="Ressources\cd.png" />
	  <None Remove="Ressources\check.png" />
	  <None Remove="Ressources\CopyFile.png" />
	  <None Remove="Ressources\deploy.png" />
	  <None Remove="Ressources\done.png" />
	  <None Remove="Ressources\erreur.png" />
	  <None Remove="Ressources\fail.png" />
	  <None Remove="Ressources\gear.png" />
	  <None Remove="Ressources\hard_disk.png" />
	  <None Remove="Ressources\ok.png" />
	  <None Remove="Ressources\pause.png" />
	  <None Remove="Ressources\ready.png" />
	  <None Remove="Ressources\resume.png" />
	  <None Remove="Ressources\stop.png" />
	  <None Remove="Ressources\success.png" />
	  <None Remove="Ressources\usb.png" />
	  <None Remove="Ressources\wait.png" />
	  <None Remove="Ressources\warning.png" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Ressources\archive.png" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="MainWindow.xaml.cs.old.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Management" Version="10.0.12" />
	</ItemGroup>


	<ItemGroup>
		<Reference Include="PB.BZH.Help.Core">
			<HintPath>..\..\PB.BZH.Help.Core\PB.BZH.Help.Core\bin\Release\net10.0-windows\PB.BZH.Help.Core.dll</HintPath>
		</Reference>
		<Reference Include="PB.BZH.Help.Wpf">
			<HintPath>..\..\PB.BZH.Help.Wpf\PB.BZH.Help.Wpf\bin\Release\net10.0-windows\PB.BZH.Help.Wpf.dll</HintPath>
		</Reference>
		<Reference Include="PB.BZH.Licensing.Core">
			<HintPath>..\..\PB.BZH.Licensing.Core\PB.BZH.Licensing.Core\bin\Release\net10.0-windows\PB.BZH.Licensing.Core.dll</HintPath>
		</Reference>
		<Reference Include="PB.BZH.Licensing.Wpf">
			<HintPath>..\..\PB.BZH.Licensing.Wpf\PB.BZH.Licensing.Wpf\bin\Release\net10.0-windows\PB.BZH.Licensing.Wpf.dll</HintPath>
		</Reference>
		<Reference Include="PB.BZH.Theme">
		  <HintPath>..\..\PB.BZH.Theming\PB.BZH.Theme\bin\Release\net10.0-windows\PB.BZH.Theme.dll</HintPath>
		</Reference>
	</ItemGroup>


	<ItemGroup>
	  <Resource Include="Ressources\alarme.png" />
	  <Resource Include="Ressources\build.png" />
	  <Resource Include="Ressources\cd.png" />
	  <Resource Include="Ressources\check.png" />
	  <Resource Include="Ressources\CopyFile.png" />
	  <Resource Include="Ressources\deploy.png" />
	  <Resource Include="Ressources\done.png" />
	  <Resource Include="Ressources\erreur.png" />
	  <Resource Include="Ressources\fail.png" />
	  <Resource Include="Ressources\gear.png" />
	  <Resource Include="Ressources\hard_disk.png" />
	  <Resource Include="Ressources\ok.png" />
	  <Resource Include="Ressources\pause.png" />
	  <Resource Include="Ressources\ready.png" />
	  <Resource Include="Ressources\resume.png" />
	  <Resource Include="Ressources\stop.png" />
	  <Resource Include="Ressources\success.png" />
	  <Resource Include="Ressources\usb.png" />
	  <Resource Include="Ressources\wait.png" />
	  <Resource Include="Ressources\warning.png" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="Ressources\Application.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
