@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

:: =================================================
:: DISKPREP.CMD - GENERATED BY DEPLOYCONFIGURATOR
:: WINPE WINDOWS 10/11
:: =================================================

:: ==============================
:: CONFIGURATION GENERATED
:: ==============================
set "FIRMWARE_MODE=__FIRMWARE_MODE__"
set "LAYOUT_MODE=__LAYOUT_MODE__"

set "OS_DISK=__OS_DISK__"
set "DATA_DISK=__DATA_DISK__"
set "SEPARATE_DATA_DISK=__SEPARATE_DATA_DISK__"

set "WINDOWS_SIZE_MB=__WINDOWS_SIZE_MB__"
set "EFI_SIZE_MB=__EFI_SIZE_MB__"
set "MSR_SIZE_MB=__MSR_SIZE_MB__"
set "SYSTEM_SIZE_MB=__SYSTEM_SIZE_MB__"
set "RECOVERY_SIZE_MB=__RECOVERY_SIZE_MB__"

set "IMAGE_INDEX=__IMAGE_INDEX__"

set "CREATE_DATA1=__CREATE_DATA1__"

set "BOOT_LETTER=__BOOT_LETTER__"
set "WINDOWS_LETTER=__WINDOWS_LETTER__"
set "RECOVERY_LETTER=__RECOVERY_LETTER__"
set "DATA1_LETTER=__DATA1_LETTER__"

set "LABEL_BOOT_BIOS=__LABEL_BOOT_BIOS__"
set "LABEL_BOOT_UEFI=__LABEL_BOOT_UEFI__"
set "LABEL_WINDOWS=__LABEL_WINDOWS__"
set "LABEL_RECOVERY=__LABEL_RECOVERY__"
set "LABEL_DATA1=__LABEL_DATA1__"

set "DATA2_DISK=__DATA2_DISK__"
set "DUAL_DATA_DISK=__DUAL_DATA_DISK__"
set "CREATE_DATA2=__CREATE_DATA2__"

set "DATA2_LETTER=__DATA2_LETTER__"
set "LABEL_DATA2=__LABEL_DATA2__"

set "INSTALL_IMAGE=__INSTALL_IMAGE__"
set "IMAGE_TYPE=__IMAGE_TYPE__"
set "IMAGE_INDEX=__IMAGE_INDEX__"

set "BOOT_MARKER=__BOOT_MARKER__"
set "WINDOWS_MARKER=__WINDOWS_MARKER__"
set "RECOVERY_MARKER=__RECOVERY_MARKER__"
set "DATA1_MARKER=__DATA1_MARKER__"
set "DATA2_MARKER=__DATA2_MARKER__"

:: ==============================
:: INIT LOG SYSTEM WINPE
:: ==============================
set "LOGROOT=X:\WinPE\Logs"
if not exist "%LOGROOT%" mkdir "%LOGROOT%"
set "LOGFILE=%LOGROOT%\diskprep.log"

echo [%DATE% %TIME:~0,8%] Démarrage du script>> "%LOGFILE%"
call :LOG "====================== START DISKPREP ============================"

:: ==============================
:: DETECTION MODE BIOS/UEFI
:: ==============================
call :LOG "DETECTION MODE BIOS/UEFI"
call :EXEC_CRITICAL "wpeutil UpdateBootInfo"

if /I "%FIRMWARE_MODE%"=="BIOS" (
    set "MODE=BIOS"
    goto :MODE_OK
)

if /I "%FIRMWARE_MODE%"=="UEFI" (
    set "MODE=UEFI"
    goto :MODE_OK
)

for /f "tokens=3" %%i in ('reg query HKLM\System\CurrentControlSet\Control /v PEFirmwareType 2^>nul') do set "FW=%%i"

if "%FW%"=="0x1" (
    set "MODE=BIOS"
) else (
    set "MODE=UEFI"
)

:MODE_OK
call :LOG "Mode=%MODE%"

:: ==============================
:: VALIDATION CONFIG
:: ==============================
call :LOG "VALIDATION CONFIG"

if "%OS_DISK%"=="" (
    call :LOG "ERROR: OS_DISK is empty"
    goto :FAIL
)

if /I "%SEPARATE_DATA_DISK%"=="YES" (
    if "%DATA_DISK%"=="" (
        call :LOG "ERROR: DATA_DISK is empty while SEPARATE_DATA_DISK=YES"
        goto :FAIL
    )

    if "%DATA_DISK%"=="%OS_DISK%" (
        call :LOG "ERROR: DATA_DISK cannot be equal to OS_DISK"
        goto :FAIL
    )
)

:: ==============================
:: 1 - GENERATE DISKPART FILE
:: ==============================
call :LOG "1 - GENERATE DISKPART FILE"

set "DP=X:\WinPE\Scripts\diskpart.txt"
if not exist "X:\WinPE\Scripts" mkdir "X:\WinPE\Scripts"

(
    echo select disk %OS_DISK%
    echo clean
) > "%DP%"

if /I "%MODE%"=="BIOS" (
    (
        echo convert mbr
    ) >> "%DP%"
) else ( 
        echo convert gpt
) >> "%DP%"
(
    echo create partition primary size=%RECOVERY_SIZE_MB%
    echo format fs=ntfs quick label=%LABEL_RECOVERY%
    echo assign letter=%RECOVERY_LETTER%
) >> "%DP%"
if /I "%MODE%"=="BIOS" (
    (
        echo create partition primary size=%SYSTEM_SIZE_MB%
        echo format fs=ntfs quick label=%LABEL_BOOT_BIOS%
        echo active
        echo assign letter=%BOOT_LETTER%
    ) >> "%DP%"
) else (
    (
        echo create partition efi size=%EFI_SIZE_MB%
        echo format fs=fat32 quick label=%LABEL_BOOT_UEFI%
        echo assign letter=%BOOT_LETTER%
        echo create partition msr size=%MSR_SIZE_MB%
    ) >> "%DP%"
)
(
    echo create partition primary size=%WINDOWS_SIZE_MB%
    echo format fs=ntfs quick label=%LABEL_WINDOWS%
    echo assign letter=%WINDOWS_LETTER%
) >> "%DP%"

if /I "%CREATE_DATA1%"=="YES" (
    if /I "%SEPARATE_DATA_DISK%"=="YES" (
        (
            echo select disk %DATA_DISK%
            echo clean
        ) >> "%DP%"
        if /I "%MODE%"=="BIOS" (
            echo convert mbr >> "%DP%"
        ) else (
            echo convert gpt >> "%DP%"
        ) >> "%DP%"
        (
            echo create partition primary
            echo format fs=ntfs quick label=%LABEL_DATA1%
            echo assign letter=%DATA1_LETTER%
        ) >> "%DP%"
    ) else (
        (
            echo create partition primary
            echo format fs=ntfs quick label=%LABEL_DATA1%
            echo assign letter=%DATA1_LETTER%
        ) >> "%DP%"
    )
)

if /I "%CREATE_DATA2%"=="YES" (
    if /I "%DUAL_DATA_DISK%"=="YES" (
        (
            echo select disk %DATA2_DISK%
            echo clean
        ) >> "%DP%"

        if /I "%MODE%"=="BIOS" (
            echo convert mbr >> "%DP%"
        ) else (
            echo convert gpt >> "%DP%"
        )

        (
            echo create partition primary
            echo format fs=ntfs quick label=%LABEL_DATA2%
            echo assign letter=%DATA2_LETTER%
        ) >> "%DP%"
    )
)

call :LOG "Contenu diskpart généré :"
type "%DP%" >> "%LOGFILE%" 2>&1

call :LOG "EXECUTION DISKPART"
call :EXEC_CRITICAL "diskpart /s %DP%"

:: ==============================
:: 2 - CREATING MARKERS
:: ==============================
call :LOG "2 - CREATING MARKERS"

if /I "%MODE%"=="UEFI" (
    set "BOOTMARKER=EFI"
) else (
    set "BOOTMARKER=SYSTEM"
)

call :LOG "Marqueur de boot: %BOOTMARKER%"

call :EXEC_CRITICAL "echo %BOOTMARKER% > %BOOT_LETTER%:\%BOOT_MARKER%"
call :EXEC_CRITICAL "echo WINDOWS > %WINDOWS_LETTER%:\%WINDOWS_MARKER%"
call :EXEC_CRITICAL "echo RECOVERY > %RECOVERY_LETTER%:\%RECOVERY_MARKER%"

attrib +h +s %BOOT_LETTER%:\%BOOT_MARKER% 2>nul
attrib +h +s %WINDOWS_LETTER%:\%WINDOWS_MARKER% 2>nul
attrib +h +s %RECOVERY_LETTER%:\%RECOVERY_MARKER% 2>nul
if /I "%CREATE_DATA1%"=="YES" (
    call :EXEC_CRITICAL "echo DATA-1 > %DATA1_LETTER%:\%DATA1_MARKER%"
    attrib +h +s %DATA1_LETTER%:\%DATA1_MARKER% 2>nul
)
if /I "%CREATE_DATA2%"=="YES" (
    call :EXEC_CRITICAL "echo DATA-2 > %DATA2_LETTER%:\%DATA2_MARKER%"
    attrib +h +s %DATA2_LETTER%:\%DATA2_MARKER% 2>nul
)

call :FINDDRIVE "%WINDOWS_MARKER%" "WINVOL"
call :FINDDRIVE "%BOOT_MARKER%" "SYSVOL"
call :FINDDRIVE "%RECOVERY_MARKER%" "RECVOL"
if /I "%CREATE_DATA1%"=="YES" (
    call :FINDDRIVE "%DATA1_MARKER%" "DATAVOL"
)
if /I "%CREATE_DATA2%"=="YES" (
    call :FINDDRIVE "%DATA2_MARKER%" "DATA2VOL"
)

call :LOG "Windows = %WINVOL%"
call :LOG "System  = %SYSVOL%"
call :LOG "Recovery= %RECVOL%"
call :LOG "Data-1  = %DATAVOL%"
call :LOG "Data-2  = %DATA2VOL%"

if not defined WINVOL (
    call :LOG "ERROR: Windows volume not found"
    goto :FAIL
)

if not defined SYSVOL (
    call :LOG "ERROR: System volume not found"
    goto :FAIL
)

if not defined RECVOL (
    call :LOG "ERROR: Recovery volume not found"
    goto :FAIL
)

if /I "%CREATE_DATA1%"=="YES" (
    if not defined DATAVOL (
        call :LOG "ERROR: DATA-1 volume not found"
        goto :FAIL
    )
)

:: ==============================
:: 3 - APPLY IMAGE WINDOWS
:: ==============================
call :LOG "3 - APPLY IMAGE WINDOWS"

call :FINDDRIVE "setup.exe" "MEDIA"
call :LOG "Media=%MEDIA%"

if not defined MEDIA (
    call :LOG "ERROR: Windows installation media not found"
    goto :FAIL
)

set "IMAGEFILE="
set "SWMFILE="
set "IMAGE_TYPE_RESOLVED="

if /I "%IMAGE_TYPE%"=="WIM" (
    set "IMAGEFILE=%MEDIA%\sources\install.wim"
    set "IMAGE_TYPE_RESOLVED=WIM"
)

if /I "%IMAGE_TYPE%"=="SWM" (
    set "IMAGEFILE=%MEDIA%\sources\install.swm"
    set "SWMFILE=%MEDIA%\sources\install*.swm"
    set "IMAGE_TYPE_RESOLVED=SWM"
)

if /I "%IMAGE_TYPE%"=="ESD" (
    set "IMAGEFILE=%MEDIA%\sources\install.esd"
    set "IMAGE_TYPE_RESOLVED=ESD"
)

if /I "%IMAGE_TYPE%"=="AUTO" (
    if exist "%MEDIA%\sources\install.wim" (
        set "IMAGEFILE=%MEDIA%\sources\install.wim"
        set "IMAGE_TYPE_RESOLVED=WIM"
    )

    if not defined IMAGEFILE (
        if exist "%MEDIA%\sources\install.esd" (
            set "IMAGEFILE=%MEDIA%\sources\install.esd"
            set "IMAGE_TYPE_RESOLVED=ESD"
        )
    )

    if not defined IMAGEFILE (
        if exist "%MEDIA%\sources\install.swm" (
            set "IMAGEFILE=%MEDIA%\sources\install.swm"
            set "SWMFILE=%MEDIA%\sources\install*.swm"
            set "IMAGE_TYPE_RESOLVED=SWM"
        )
    )
)

if not defined IMAGEFILE (
    call :LOG "ERROR: no Windows image file selected or detected"
    goto :FAIL
)

if not exist "%IMAGEFILE%" (
    call :LOG "ERROR: selected image file not found: %IMAGEFILE%"
    goto :FAIL
)

call :LOG "Image type=%IMAGE_TYPE_RESOLVED%"
call :LOG "Image file=%IMAGEFILE%"
call :LOG "Image index=%IMAGE_INDEX%"

if /I "%IMAGE_TYPE_RESOLVED%"=="SWM" (
    call :LOG "SWM file pattern=%SWMFILE%"

    call :EXEC_CRITICAL "dism /apply-image /imagefile:%IMAGEFILE% /swmfile:%SWMFILE% /index:%IMAGE_INDEX% /applydir:%WINVOL%\"
) else (
    call :EXEC_CRITICAL "dism /apply-image /imagefile:%IMAGEFILE% /index:%IMAGE_INDEX% /applydir:%WINVOL%\"
)

:: ==============================
:: 4 - CONFIGURE BOOT
:: ==============================
call :LOG "4 - CONFIGURE BOOT"

if /I "%MODE%"=="UEFI" (
    call :EXEC_CRITICAL "bcdboot %WINVOL%\Windows /s %SYSVOL% /f UEFI"
) else (
    call :EXEC_CRITICAL "bcdboot %WINVOL%\Windows /s %SYSVOL% /f BIOS"
)

:: =================================================
:: 5 - COPY DEPLOY FILES
:: =================================================
call :LOG "5 - COPY DEPLOY FILES"

if not exist "%WINVOL%\Deploy\WinPE" mkdir "%WINVOL%\Deploy\WinPE"
if not exist "%WINVOL%\Deploy\WinPE\Scripts" mkdir "%WINVOL%\Deploy\WinPE\Scripts"
if not exist "%WINVOL%\Deploy\Setup" mkdir "%WINVOL%\Deploy\Setup"
if not exist "%WINVOL%\Windows\Panther" mkdir "%WINVOL%\Windows\Panther"
if not exist "%WINVOL%\Windows\Setup\Scripts" mkdir "%WINVOL%\Windows\Setup\Scripts"

set "LOCAL_SCRIPTS=%WINVOL%\Deploy\Setup\Scripts"
set "CONFIG_SCRIPTS=%WINVOL%\Deploy\Setup\Config"

call :EXEC_CRITICAL "xcopy %MEDIA%\Deploy\WinPE\* %WINVOL%\Deploy\WinPE\ /E /Y /I"
call :EXEC_CRITICAL "xcopy %MEDIA%\Deploy\Setup\* %WINVOL%\Deploy\Setup\ /E /Y /I"
call :EXEC_CRITICAL "xcopy X:\WinPE\* %WINVOL%\Deploy\WinPE\ /E /Y /I"

call :EXEC_CRITICAL "copy %LOCAL_SCRIPTS%\SetupComplete.cmd %WINVOL%\Windows\Setup\Scripts\SetupComplete.cmd /Y"
call :EXEC_CRITICAL "copy %CONFIG_SCRIPTS%\unattend.xml %WINVOL%\Windows\Panther\unattend.xml /Y"

:: =================================================
:: 6 - COPY SOFTWARES AND DRIVERS TO DATA-1
:: =================================================
call :LOG "6 - COPY SOFTWARES AND DRIVERS TO DATA-1"

if /I "%CREATE_DATA1%"=="YES" (
    if not exist "%DATAVOL%\Logiciels" mkdir "%DATAVOL%\Logiciels"
    if not exist "%DATAVOL%\Drivers" mkdir "%DATAVOL%\Drivers"

    call :EXEC_CRITICAL "xcopy %MEDIA%\Deploy\Logiciels\* %DATAVOL%\Logiciels\ /E /Y /I"
    call :EXEC_CRITICAL "xcopy %MEDIA%\Deploy\Drivers\* %DATAVOL%\Drivers\ /E /Y /I"
)

:: ==============================
:: 7 - COPY LOGS TO WINDOWS
:: ==============================
call :LOG "7 - COPY LOGS TO WINDOWS"

call :COPYFROMVOLUMES "\WinPE\Logs\diskprep.log" "WinPE\Logs" "%WINVOL%\Deploy\WinPE\Logs" "%LOGFILE%"

:: ==============================
:: 8 - REBOOT TO INSTALLED OS
:: ==============================
call :LOG "8 - REBOOT TO INSTALLED OS"
call :LOG "==================== END DISKPREP =========================="

call :EXEC_CRITICAL "wpeutil reboot"

endlocal
exit /b 0

:: =================================================
:: FAIL
:: =================================================
:FAIL
call :LOG "==================== DISKPREP FAILED ======================="
call :LOG "Script arrêté sur erreur critique."
endlocal
exit /b 1

:: ==========================
:: FONCTION :LOG
:: ==========================
:LOG
echo [%DATE% %TIME:~0,8%] %~1>> "%LOGFILE%" 2>&1
goto :eof

:: ==========================
:: FONCTION :EXEC
:: ==========================
:EXEC
echo [%DATE% %TIME:~0,8%] EXEC: %~1>> "%LOGFILE%" 2>&1
cmd /c "%~1" >> "%LOGFILE%" 2>&1
set "RC=%ERRORLEVEL%"
if not "%RC%"=="0" call :LOG "WARNING RC=%RC% : %~1"
goto :eof

:: ==========================
:: FONCTION :EXEC_CRITICAL
:: ==========================
:EXEC_CRITICAL
echo [%DATE% %TIME:~0,8%] EXEC_CRITICAL: %~1>> "%LOGFILE%" 2>&1
cmd /c "%~1" >> "%LOGFILE%" 2>&1
set "RC=%ERRORLEVEL%"
if not "%RC%"=="0" (
    call :LOG "FATAL ERROR RC=%RC% : %~1"
    goto :FAIL
)
goto :eof

:: ==========================
:: FONCTION :COPYFROMVOLUMES
:: ==========================
:COPYFROMVOLUMES
setlocal enabledelayedexpansion
set "SEARCH=%~1"
set "SRC=%~2"
set "DEST=%~3"
set "LOCAL_LOGFILE=%~4"

for %%i in (D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
    if exist "%%i:\!SEARCH!" (
        echo [%DATE% %TIME:~0,8%] Found on %%i: >> "!LOCAL_LOGFILE!"
        mkdir "!DEST!" 2>nul
        xcopy "%%i:\!SRC!\*" "!DEST!\" /E /Y /I >> "!LOCAL_LOGFILE!" 2>&1
    )
)

endlocal
goto :eof

:: ==========================
:: FONCTION :FINDDRIVE
:: ==========================
:FINDDRIVE
setlocal enabledelayedexpansion
set "MARKER=%~1"
set "RESULT="

for %%i in (D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
    if exist "%%i:\!MARKER!" (
        set "RESULT=%%i:"
        goto :FOUND
    )
)

:FOUND
endlocal & set "%~2=%RESULT%"
goto :eof