@echo off
chcp 65001 >nul
setlocal EnableDelayedExpansion
set "RESUME_ONLY=%~1"
:: ==================================================
:: DEPLOY OS PRO - ORCHESTRATOR RESUME
:: Reprise automatique après reboot
:: ==================================================

:: ==================================================
:: 0 - CONFIGURATION
:: ==================================================
set "DEPLOYROOT=C:\Deploy"
set "SETUPROOT=%DEPLOYROOT%\Setup"
set "SCRIPTROOT=%SETUPROOT%\Scripts"
set "CONFIGROOT=%SETUPROOT%\Config"
set "LOGROOT=%SETUPROOT%\Logs"
set "REPORTROOT=%SETUPROOT%\Reports"
set "STATEROOT=%SETUPROOT%\State"

set "LOGFILE=%LOGROOT%\orchestrator_resume.log"
set "REPORT=%REPORTROOT%\deploy_report.log"
set "STATEFILE=%STATEROOT%\resume.step"
set "RESUME_TASK=DeployResume"

if not exist "%LOGROOT%" mkdir "%LOGROOT%" 2>nul
if not exist "%REPORTROOT%" mkdir "%REPORTROOT%" 2>nul
if not exist "%STATEROOT%" mkdir "%STATEROOT%" 2>nul

call :LOG "=================================================="
call :LOG "ORCHESTRATOR RESUME START"
call :LOG "=================================================="
call :LOG "STATEFILE=%STATEFILE%"
call :LOG "ARGUMENTS=%*"
call :LOG "RESUME_ONLY=%RESUME_ONLY%"

:: ==================================================
:: MODE RESUME ONLY
:: ==================================================
if /I "%RESUME_ONLY%"=="RESUMEONLY" (
    if not exist "%STATEFILE%" (
        call :LOG "RESUMEONLY requested but no resume state found. Exiting."
        endlocal
        exit /b 0
    )
)

:: ==================================================
:: 1 - LECTURE ETAT DE REPRISE
:: ==================================================
set "RESUME_STEP=01"

if exist "%STATEFILE%" (
    set /p RESUME_STEP=<"%STATEFILE%"
    call :LOG "Resume state detected: !RESUME_STEP!"
) else (
    call :LOG "No resume state found. Starting at step 01"
)

call :REPORT "DEPLOY START / RESUME_STEP=!RESUME_STEP!"


:: ==================================================
:: 2 - CONFIGURATION MODULES
:: 1 = actif / 0 = ignoré
:: Generated by DeployConfigurator
:: ==================================================
set "RUN_DETACH_USB=__RUN_DETACH_USB__"
set "RUN_REORG_VOLUMES=__RUN_REORG_VOLUMES__"
set "RUN_WIFI=__RUN_WIFI__"
set "RUN_DRIVERS=__RUN_DRIVERS__"
set "RUN_WINDOWS_UPDATE_DRIVERS=__RUN_WINDOWS_UPDATE_DRIVERS__"
set "RUN_SOFTWARES=__RUN_SOFTWARES__"
set "RUN_M365=__RUN_M365__"
set "RUN_POSTINSTALL=__RUN_POSTINSTALL__"
set "RUN_CLEANUP=__RUN_CLEANUP__"


:: ==================================================
:: 3 - ROUTAGE VERS ETAPE
:: ==================================================
if "%RESUME_STEP%"=="01" goto :STEP_01
if "%RESUME_STEP%"=="02" goto :STEP_02
if "%RESUME_STEP%"=="03" goto :STEP_03
if "%RESUME_STEP%"=="04" goto :STEP_04
if "%RESUME_STEP%"=="05" goto :STEP_05
if "%RESUME_STEP%"=="06" goto :STEP_06
if "%RESUME_STEP%"=="07" goto :STEP_07
if "%RESUME_STEP%"=="08" goto :STEP_08
if "%RESUME_STEP%"=="09" goto :STEP_09

call :LOG "ERROR: unknown resume step %RESUME_STEP%"
goto :FAIL


:: ==================================================
:: STEP 01 - DETACH USB
:: ==================================================
:STEP_01
call :LOG "STEP 01 - DETACH USB"

if "%RUN_DETACH_USB%"=="1" (
    call :RUN_CRITICAL_REBOOT "01_Detach_USB" "%SCRIPTROOT%\detach_usb.cmd" "02"
    if errorlevel 1 goto :FAIL
)


:: ==================================================
:: STEP 02 - REORG VOLUMES
:: ==================================================
:STEP_02
call :LOG "STEP 02 - REORG VOLUMES"

if "%RUN_REORG_VOLUMES%"=="1" (
    call :RUN_CRITICAL_REBOOT "02_Reorg_Volumes" "%SCRIPTROOT%\reorg_volumes.cmd" "03"
    if errorlevel 1 goto :FAIL
)


:: ==================================================
:: STEP 03 - WIFI
:: ==================================================
:STEP_03
call :LOG "STEP 03 - WIFI"

if "%RUN_WIFI%"=="1" (
    call :RUN_CRITICAL_REBOOT "03_WiFi_Connect" "%SCRIPTROOT%\network_connect.cmd" "04" "%CONFIGROOT%" "%LOGROOT%"
    if errorlevel 1 goto :FAIL
)


:: ==================================================
:: STEP 04 - INSTALL DRIVERS EXPORTED
:: ==================================================
:STEP_04
call :LOG "STEP 04 - INSTALL DRIVERS EXPORTED"

if "%RUN_DRIVERS%"=="1" (
    call :RUN_CRITICAL_REBOOT "04_Install_Drivers_Exported" "%SCRIPTROOT%\install_drivers_exported.cmd" "05"
    if errorlevel 1 goto :FAIL
)


:: ==================================================
:: STEP 05 - WINDOWS UPDATE DRIVERS
:: Optional mais reboot-aware
:: ==================================================
:STEP_05
call :LOG "STEP 05 - WINDOWS UPDATE DRIVERS"

if "%RUN_WINDOWS_UPDATE_DRIVERS%"=="1" (
    call :RUN_OPTIONAL_REBOOT "05_Windows_Update_Drivers" "%SCRIPTROOT%\windows_update_drivers.cmd" "06"
    set "RC=%ERRORLEVEL%"
    call :LOG "STEP 05 RETURNED RC=%RC%"

    if "%RC%"=="3010" (
        call :REBOOT_AND_RESUME "06"
        endlocal
        goto :REBOOT_EXIT
        exit /b 0
    )
)


:: ==================================================
:: STEP 06 - INSTALL SOFTWARES
:: ==================================================
:STEP_06
call :LOG "STEP 06 - INSTALL SOFTWARES"

if "%RUN_SOFTWARES%"=="1" (
    call :RUN_CRITICAL_REBOOT "06_Install_Softwares" "%SCRIPTROOT%\install_softwares.cmd" "07"
    if errorlevel 1 goto :FAIL
)


:: ==================================================
:: STEP 07 - INSTALL MICROSOFT 365
:: ==================================================
:STEP_07
call :LOG "STEP 07 - INSTALL MICROSOFT 365"

if "%RUN_M365%"=="1" (
    call :RUN_CRITICAL_REBOOT "07_Install_M365" "%SCRIPTROOT%\install_m365.cmd" "08"
    if errorlevel 1 goto :FAIL
)


:: ==================================================
:: STEP 08 - POSTINSTALL
:: ==================================================
:STEP_08
call :LOG "STEP 08 - POSTINSTALL"

if "%RUN_POSTINSTALL%"=="1" (
    call :RUN_CRITICAL_REBOOT "08_PostInstall" "%SCRIPTROOT%\postinstall.cmd" "09"
    if errorlevel 1 goto :FAIL
)


:: ==================================================
:: STEP 09 - CLEANUP
:: ==================================================
:STEP_09
call :LOG "STEP 09 - CLEANUP"

if "%RUN_CLEANUP%"=="1" (
    call :RUN_OPTIONAL "09_Cleanup" "%SCRIPTROOT%\cleanup.cmd"
)


:: ==================================================
:: END SUCCESS
:: ==================================================
call :CLEAR_RESUME

call :LOG "=================================================="
call :LOG "ORCHESTRATOR RESUME SUCCESS"
call :LOG "=================================================="

call :REPORT "DEPLOY SUCCESS"

endlocal
exit /b 0


:: ==================================================
:: FUNCTION :RUN_CRITICAL_REBOOT
:: %1 = step name
:: %2 = script path
:: %3 = next step if reboot required
:: %4-%6 = optional args
:: ==================================================
:RUN_CRITICAL_REBOOT
setlocal EnableDelayedExpansion

set "STEP=%~1"
set "CMD=%~2"
set "NEXTSTEP=%~3"
set "ARG1=%~4"
set "ARG2=%~5"
set "ARG3=%~6"

set "RUNLOG=%LOGROOT%\run_%STEP%.log"

call :LOG "--------------------------------------------------"
call :LOG "START CRITICAL REBOOT-AWARE %STEP%"
call :LOG "CMD=%CMD%"
call :LOG "NEXTSTEP=%NEXTSTEP%"
call :REPORT "%STEP% START"

if exist "%RUNLOG%" del /f /q "%RUNLOG%" 2>nul

if not exist "%CMD%" (
    call :LOG "ERROR: script not found: %CMD%"
    call :REPORT "%STEP% FAILED - SCRIPT NOT FOUND"
    endlocal & exit /b 1
)

set "STARTTIME=%TIME%"

call "%CMD%" "%ARG1%" "%ARG2%" "%ARG3%" >> "%RUNLOG%" 2>&1

set "RC=!ERRORLEVEL!"
set "ENDTIME=%TIME%"

call :LOG "%STEP% RC=!RC!"
call :LOG "%STEP% START=%STARTTIME% END=%ENDTIME%"
call :REPORT "%STEP% RC=!RC! START=%STARTTIME% END=%ENDTIME%"

if "!RC!"=="3010" (
    call :LOG "INFO: %STEP% requested reboot"
    call :REPORT "%STEP% REBOOT REQUIRED"
    endlocal & exit /b 3010
)

if not "!RC!"=="0" (
    call :LOG "ERROR: %STEP% failed"
    call :REPORT "%STEP% FAILED"
    endlocal & exit /b 1
)

call :LOG "END %STEP% OK"
call :REPORT "%STEP% OK"

endlocal & exit /b 0


:: ==================================================
:: FUNCTION :RUN_OPTIONAL_REBOOT
:: %1 = step name
:: %2 = script path
:: %3 = next step if reboot required
:: %4-%6 = optional args
:: ==================================================
:RUN_OPTIONAL_REBOOT
setlocal EnableDelayedExpansion

set "STEP=%~1"
set "CMD=%~2"
set "NEXTSTEP=%~3"
set "ARG1=%~4"
set "ARG2=%~5"
set "ARG3=%~6"

set "RUNLOG=%LOGROOT%\run_%STEP%.log"

call :LOG "--------------------------------------------------"
call :LOG "START OPTIONAL REBOOT-AWARE %STEP%"
call :LOG "CMD=%CMD%"
call :LOG "NEXTSTEP=%NEXTSTEP%"
call :REPORT "%STEP% START OPTIONAL REBOOT-AWARE"

if exist "%RUNLOG%" del /f /q "%RUNLOG%" 2>nul

if not exist "%CMD%" (
    call :LOG "WARN: optional script not found: %CMD%"
    call :REPORT "%STEP% SKIPPED - SCRIPT NOT FOUND"
    endlocal & exit /b 0
)

set "STARTTIME=%TIME%"

call "%CMD%" "%ARG1%" "%ARG2%" "%ARG3%" >> "%RUNLOG%" 2>&1

set "RC=!ERRORLEVEL!"
set "ENDTIME=%TIME%"

call :LOG "%STEP% RC=!RC!"
call :LOG "%STEP% START=%STARTTIME% END=%ENDTIME%"
call :REPORT "%STEP% RC=!RC! START=%STARTTIME% END=%ENDTIME%"

if "!RC!"=="3010" (
    call :LOG "INFO: %STEP% requested reboot"
    call :REPORT "%STEP% REBOOT REQUIRED"
    endlocal & exit /b 3010
)

if not "!RC!"=="0" (
    call :LOG "WARN: %STEP% failed but continues"
    call :REPORT "%STEP% WARN FAILED BUT CONTINUED"
    endlocal & exit /b 0
)

call :LOG "END OPTIONAL REBOOT-AWARE %STEP% OK"
call :REPORT "%STEP% OK"

endlocal & exit /b 0


:: ==================================================
:: FUNCTION :SAVE_STATE
:: %1 = next step after reboot
:: ==================================================
:SAVE_STATE
if not exist "%STATEROOT%" mkdir "%STATEROOT%" 2>nul
echo %~1> "%STATEFILE%"
call :LOG "State saved: next step=%~1"
goto :eof


:: ==================================================
:: FUNCTION :REBOOT_AND_RESUME
:: %1 = next step after reboot
:: ==================================================
:REBOOT_AND_RESUME
call :SAVE_STATE "%~1"

call :LOG "Reboot requested. Resume at step %~1"
call :REPORT "REBOOT REQUESTED - NEXT STEP %~1"

shutdown /r /t 0 /f

goto :REBOOT_EXIT

:: ==================================================
:: FUNCTION :CLEAR_RESUME
:: ==================================================
:CLEAR_RESUME
if exist "%STATEFILE%" del /f /q "%STATEFILE%" 2>nul
call :LOG "Resume state cleared"
goto :eof


:: ==================================================
:: FUNCTION :LOG
:: ==================================================
:LOG
echo [%DATE% %TIME:~0,8%] %~1>> "%LOGFILE%"
goto :eof


:: ==================================================
:: FUNCTION :REPORT
:: ==================================================
:REPORT
echo [%DATE% %TIME:~0,8%] %~1>> "%REPORT%"
goto :eof


:: ==================================================
:: REBOOT EXIT
:: ==================================================
:REBOOT_EXIT
call :LOG "ORCHESTRATOR STOPPED FOR REBOOT"
endlocal
exit /b 0

:: ==================================================
:: FAIL
:: ==================================================
:FAIL
call :LOG "=================================================="
call :LOG "ORCHESTRATOR FAILED"
call :LOG "=================================================="

call :REPORT "DEPLOY FAILED"

endlocal
exit /b 1