@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

:: ==================================================
:: SETUPCOMPLETE.CMD - GENERATED BY DEPLOYCONFIGURATOR
:: ==================================================

set "DEPLOYROOT=C:\Deploy"
set "SCRIPTROOT=%DEPLOYROOT%\Setup\Scripts"
set "LOGROOT=%DEPLOYROOT%\Setup\Logs"

if not exist "%LOGROOT%" mkdir "%LOGROOT%"

set "LOGFILE=%LOGROOT%\setupcomplete.log"

echo [%DATE% %TIME:~0,8%] START SETUPCOMPLETE>> "%LOGFILE%"

if exist "%SCRIPTROOT%\orchestrator_resume.cmd" (
    echo [%DATE% %TIME:~0,8%] RUN ORCHESTRATOR>> "%LOGFILE%"
    call "%SCRIPTROOT%\orchestrator_resume.cmd" >> "%LOGFILE%" 2>&1
) else (
    echo [%DATE% %TIME:~0,8%] ERROR orchestrator_resume.cmd not found>> "%LOGFILE%"
)

echo [%DATE% %TIME:~0,8%] END SETUPCOMPLETE>> "%LOGFILE%"

endlocal
exit /b 0